name: bbl_security
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter_otp_text_field: ^1.1.0+2
  local_auth: ^2.2.0
  country_picker: ^2.0.16
  pattern_lock: ^2.0.0
  font_awesome_flutter: ^10.1.0
  http: ^1.2.2
  regexed_validator: ^2.0.0+1
  email_validator: ^3.0.0
  logging: ^1.2.0
  pin_code_fields: ^8.0.1
  flutter_localization: ^0.2.1
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/logo.svg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.svg
    - assets/faceauth.svg
  

